### ISSUE TITLE
Last.fm not working

### ISSUE THREAD

**Issue by dolivo** [gqgs/3x3-generator#273] opened 2024-03-18 19:32 UTC
Last.fm album covers are not loading

**Comment by gqgs** [comment] 2024-03-19 11:27
@dolivo Hello. Thanks for the report. Is it still broken for you? Seems to be working fine in some tests I did.

![image](https://github.com/gqgs/3x3-generator/assets/32180229/27afa51a-14fa-4c1b-8790-9f682d5fcdb4)

**Comment by gqgs** [comment] 2024-03-29 20:50
Closing this since we haven't been provided steps for a reproduction.
Feel free to reopen with the reproduction steps if it's still an issue.

**Closed by gqgs** 2024-03-29 20:50 UTC
